#!/bin/bash
#
# This is a basic test on the minus-linecircle commandline
# This should run on the cloud continuously, before the detailed benchmarking
# As well as any time you make a change
#
#set -x
minus_linecircle=$HOME/cprg/vxlprg/lemsvpe/minus-bin/bin/minus-linecircle
#minus_linecircle=$HOME/cprg/vxlprg/lemsvpe/minus-bin-rel/bin/minus-linecircle
# synthdata $* | ${minus_chicago} --image_data -gt $minus_args; solver_fail="${PIPESTATUS[1]}"


# ANSI escape codes for colors
WHITE_FG="\e[97m"  # Bright white foreground
RED_BG="\e[41m"    # Red background
GREEN_BG="\e[42m"  # Green background
RESET_COLOR="\e[0m" # Reset to default colors

success="${WHITE_FG}${GREEN_BG}TEST PASS -------------------------------------------------------------${RESET_COLOR}"
fail="${WHITE_FG}${RED_BG}TEST FAIL -------------------------------------------------------------${RESET_COLOR}"

pt() {
  if [[ "$solver_fail" -ne 0 ]]; then
    solver_fail=1;
  fi
    
  if [[ "$solver_fail" == "$desired_outcome" ]]; then
    echo -e "$success"
  else
    echo -e "$fail"
  fi
}

# outcom 0 ok, nonzero fail

# Test 1 -----------------------------------------------------------------------


desired_outcome=0
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
1 0 0 0  0 0
0 0
1 0
0 0
-1 0
' | $minus_linecircle -i -gt;     solver_fail="${PIPESTATUS[1]}"
pt


desired_outcome=1
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
1 0 0 0  0 0
0 0
0 0
0 0
0 0
' | $minus_linecircle -i -gt;     solver_fail="${PIPESTATUS[1]}"
pt

# first point ok but not second
desired_outcome=1
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
1 0 0 0  0 0
0 0
1 0
0 0
0 -1
' | $minus_linecircle -i -gt;     solver_fail="${PIPESTATUS[1]}"
pt


# Test 2 -----------------------------------------------------------------------
# Like test 1 but y=0
desired_outcome=0
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
0 0 1 0  0 0
1 0
0 0
-1 0
0 0
' | $minus_linecircle -i -gt 2>/tmp/bla;     solver_fail="${PIPESTATUS[1]}"
pt
nfound=`grep "found solution at" /tmp/bla|wc -l`
nwant=2
if [[ "$nfound" -eq "$nwant" ]]; then
  echo "NSOLS PASS ---------------------------------------------------------------";
fi
pt

desired_outcome=1
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
0 0 1 0  0 0
0 0
0 0
0 0
0 -1 
' | $minus_linecircle -i -gt;     solver_fail="${PIPESTATUS[1]}"
pt

# Test 3 -----------------------------------------------------------------------
# Mixed good gt root, bad gt root

# Like test 1 but y=0
desired_outcome=1
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
0 0 1 0  0 0
1 -5
0 0
-1 0
0 0
' | $minus_linecircle -i -gt 2>/tmp/bla;     solver_fail="${PIPESTATUS[1]}"
nfound=`grep "found solution at" /tmp/bla|wc -l`
nwant=1
if [[ "$nfound" -eq "$nwant" ]]; then
  echo "NSOLS PASS ---------------------------------------------------------------";
fi
pt



desired_outcome=1
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
0 0 1 0  0 0
1 -5
0 0
-1 0
0 -3
' | $minus_linecircle -i -gt 2>/tmp/bla;     solver_fail="${PIPESTATUS[1]}"
nfound=`grep "found solution at" /tmp/bla|wc -l`
nwant=0
if [[ "$nfound" -eq "$nwant" ]]; then
  echo "NSOLS PASS ---------------------------------------------------------------";
fi
pt


desired_outcome=1
# a b c  (real and imaginary)
# d e f
# x      (ground truth x, y)
# y
echo '
1 0 0 0 -1 0
0 0 1 0  0 0
1 0
0 0
-1 0
0 -3
' | $minus_linecircle -i -gt 2>/tmp/bla;     solver_fail="${PIPESTATUS[1]}"
nfound=`grep "found solution at" /tmp/bla|wc -l`
nwant=1
if [[ "$nfound" -eq "$nwant" ]]; then
  echo "NSOLS PASS ---------------------------------------------------------------";
fi
pt

# echo '43.2791724282098 0 -4231.74135919786 0 180846142.794321 0 
#       2.38407393718674 0 5.55345331760358 0 -190.605487662164 0
#       56.4991320882471 0
#       10.0671377212599 0
#       50.9456787706435 0
#       12.4512116584466 0
#       ' | minus-linecircle -i -gt


# echo '
# 1 1 1 1  1 1
# 1 1 1 1  1 1
# ' | ./minus-linecircle -i; 
