name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-tests:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,  macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        working-directory: ./build
        run: |
          cmake ../
        shell: bash

      - name: Build
        working-directory: ./build
        run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
              cmake --build . --config Release
           else
              cmake --build . -- -j$(nproc)
           fi
        shell: bash